openapi: 3.0.0
info:
  version: 0.0.0
  title: Exhale User API
servers:
  - url: "http://localhost:1323/"
paths:
  /:
    get:
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: "Hello, World!"
